### PR TITLE
Agones2

### PR DESCRIPTION
**Pull request by mrniket**
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232)

### CODE REVIEW

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232)* status: all files reviewed, 7 unresolved discussions (waiting on @mrniket)

___
*[build.sh, line 19 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232#-MShjMpv-HEeH3EWevln:-MShjMpw7aaOxyBRVYht:b-v8b3m0) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c625f7420341425324efd14b8f98da835e740bcf/build.sh#L19)):*
> ```Shell
>     pip install -t lib --upgrade --no-deps aimmo
> else
>     pip install -t lib --pre --upgrade --no-deps git+https://github.com/ocadotechnology/aimmo.git@agones2
> ```

Need to remove this (after we test again on dev, and before we merge in)
___
*[deploy.sh, line 34 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232#-MShk91w-khhTDZgRByL:-MShk91w-khhTDZgRByM:bo5u5x5) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c625f7420341425324efd14b8f98da835e740bcf/deploy.sh#L34)):*
> ```Shell
> 
> # Deploy the correct kubernetes cluster.
> # python clusters_setup/deploy.py "${MODULE_NAME}"
> ```

Need to uncomment? (after we test again on dev, and before we merge in)
___
*[deploy.sh, line 37 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232#-MShkAkI4k9Mv6giUAdu:-MShkAkI4k9Mv6giUAdv:b-i2zxzv) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c625f7420341425324efd14b8f98da835e740bcf/deploy.sh#L37)):*
> ```Shell
> 
> 
> # ./manage.py migrate --no-input
> ```

Definitely need to uncomment (after we test again on dev, and before we merge in)
___
*[generate_requirements.py, line 8 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232#-MShkH09Ab5n27oYtWUD:-MShkH09Ab5n27oYtWUE:bhmrlv2) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c625f7420341425324efd14b8f98da835e740bcf/generate_requirements.py#L8)):*
> ```Python
>     [
>         f"codeforlife-portal=={portal_version}",
>         "git+https://github.com/ocadotechnology/aimmo.git@agones2",
> ```

Need to revert to previous here too (after we test again on dev, and before we merge in)

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232)* status: all files reviewed, 7 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[deploy.sh, line 34 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232#-MShk91w-khhTDZgRByL:-MSi3O-3CQZpARGNVCJT:b-s71wmo) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c625f7420341425324efd14b8f98da835e740bcf/deploy.sh#L34)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Need to uncomment? (after we test again on dev, and before we merge in)
</blockquote></details>

We may not need to - this may be done by terraform now, not entirely sure. We should try a fresh deployment on dev first :slightly_smiling_face: 
___
*[deploy.sh, line 37 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232#-MShkAkI4k9Mv6giUAdu:-MSi3evCBZgclggenRXo:b2y18nv) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c625f7420341425324efd14b8f98da835e740bcf/deploy.sh#L37)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Definitely need to uncomment (after we test again on dev, and before we merge in)
</blockquote></details>

I think so as well - it was probably commented out to speed up testing.

**Review by razvan-pro — COMMENTED** [review]
> Reviewed 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232)* status: all files reviewed, 5 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[clusters_setup/terraform/state.tf, line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232#-MSglr3I7Ow23tr6FVly:-MTMKkek2ZgT6rbPiWEx:b-87nps4) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/6d7dc3650a17e6327c9ff7e9594b4ca658b024fb/clusters_setup/terraform/state.tf#L23)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

We should try using `agones_version` here instead of the hardcoded version - I think it should work.
</blockquote></details>

Terraform doesn't allow variables here :shrug:

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 15 of 16 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232)* status: all files reviewed, 6 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[clusters_setup/deploy.py, line 82 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232#-MUEwLg8ABpPxHzIfLj0:-MUEwLg8ABpPxHzIfLj1:b5ok00c) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/738700c01664baf5838989f088bfdf14eb97d914/clusters_setup/deploy.py#L82)):*
> ```Python
>         )
>         env_variables[game_api_url_index]["value"] = game_api_url
>         content["spec"]["template"]["spec"]["template"]["spec"]["containers"][0][
> ```

For ease of reading this in the future, should we refactor `content["spec"]["template"]["spec"]["template"]["spec"]["containers"][0]` as a variable called `container` and use it to get the env vars and the image so we don't repeat the long list of indices?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232)* status: all files reviewed, 6 unresolved discussions (waiting on @faucomte97 and @mrniket)

___
*[clusters_setup/deploy.py, line 82 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232#-MUEwLg8ABpPxHzIfLj0:-MUF-nYy5nZ2RWawFiUe:b-l4lydw) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/738700c01664baf5838989f088bfdf14eb97d914/clusters_setup/deploy.py#L82)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

For ease of reading this in the future, should we refactor `content["spec"]["template"]["spec"]["template"]["spec"]["containers"][0]` as a variable called `container` and use it to get the env vars and the image so we don't repeat the long list of indices?
</blockquote></details>

On this line, we use that expression to set the image. While it may work to say `container['image'] = contanier_image`, we'll actually change `content` which can be confusing :slightly_smiling_face:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232#-:-MUJUFBrDj5Q2P_naEgm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by razvan-pro — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/232)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrniket)

**Pull request merged**
