### PR TITLE
feat: Deploy any branch

### PR DESCRIPTION
**Pull request by razvan-pro**
## Description
Branches can be specified when running the "Deploy to Dev" workflow - these will be built and deployed instead of the latest versions of each project.

Note: For aimmo, the Docker images from the specified branch will not be deployed at the moment. This will be done in the future.

## Motivation and Context
This allows us to easily deploy to the dev environment branches that are not ready to be merged yet.

## How Has This Been Tested?
Did some test branches in the projects, typed their name in the inputs and checked the changes were deployed to dev.

## Screenshots (if appropriate):
image

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250)* status: all files reviewed, 5 unresolved discussions (waiting on @razvan-pro)

___
*[generate_requirements.py, line 5 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4xl4-CUJFvdOoDASS:-Mj4xl4-CUJFvdOoDAST:bsi9n66) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L5)):*
> ```
> from lib.aimmo import __version__ as aimmo_version
> from lib.game import __version__ as rapid_router_version
> ```

We shouldn't be needing these anymore
___
*[generate_requirements.py, line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4xwCP5AtpjshlYiwc:-Mj4xwCP5AtpjshlYiwd:b-9mtclc) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L14)):*
> ```Python
> args = parser.parse_args()
> 
> if args.portal_branch is None:
> ```

Minor but can we flip the statement so that we just have `if args.portal_branch`, without the `is None`?
___
*[generate_requirements.py, line 23 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4y69z9BvTdkDem-iX:-Mj4y69z9BvTdkDem-iY:buo9nmt) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L23)):*
> ```Python
>     common_requirement = f"git+https://github.com/ocadotechnology/codeforlife-portal@{args.portal_branch}#egg=cfl-common&subdirectory=cfl_common"
> 
> if args.rapid_router_branch is None:
> ```

Same here
___
*[generate_requirements.py, line 28 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4y7T89avYaOPnJ-L2:-Mj4y7T99JtdP4dxzjja:buo9nmt) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L28)):*
> ```Python
>     rapid_router_requirement = f"git+https://github.com/ocadotechnology/rapid-router@{args.rapid_router_branch}#egg=rapid-router"
> 
> if args.aimmo_branch is None:
> ```

Same here
___
*[build/.gitignore, line 2 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4yhZB0OgeV7ISQ6yC:-Mj4yhZB0OgeV7ISQ6yD:b3kre) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/build/.gitignore#L2)):*
> ```ignore
> *
> !.gitignore
> ```

?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[generate_requirements.py, line 5 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4xl4-CUJFvdOoDASS:-Mj5-5CnE_tei-MMMXtZ:b-jz0sa5) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L5)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

> ```
> from lib.aimmo import __version__ as aimmo_version
> from lib.game import __version__ as rapid_router_version
> ```

We shouldn't be needing these anymore
</blockquote></details>

We do need these to deploy the latest versions :slightly_smiling_face: (when branches are None)
___
*[generate_requirements.py, line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4xwCP5AtpjshlYiwc:-Mj52m766Xp_wbe-7SxT:b4kq7et) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Minor but can we flip the statement so that we just have `if args.portal_branch`, without the `is None`?
</blockquote></details>

I think I had some edge case in mind here, but I can't remember it now :thinking: It probably wasn't important :slightly_smiling_face: 
___
*[generate_requirements.py, line 23 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4y69z9BvTdkDem-iX:-Mj52wJH2Y0nDEUGDiCO:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L23)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[generate_requirements.py, line 28 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4y7T89avYaOPnJ-L2:-Mj52wXn6OgFFDdaPC7Q:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L28)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.
___
*[build/.gitignore, line 2 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4yhZB0OgeV7ISQ6yC:-Mj5-sLJDHf1YwMFgS4t:bo7748a) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/build/.gitignore#L2)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

?
</blockquote></details>

I thought this is where aimmo gets built, but it's probably leftover from some previous attempts :sweat_smile:

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-:-Mj54xJI1JKaXfS3IJ98:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[generate_requirements.py, line 5 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4xl4-CUJFvdOoDASS:-Mj54bw21albebAyBK7A:b-mr8fmx) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L5)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

We do need these to deploy the latest versions :slightly_smiling_face: (when branches are None)
</blockquote></details>

Oh yeah, I didn't see the portal was below. Shall we group them all up here or is there a reason the portal one is imported later?
___
*[generate_requirements.py, line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4xwCP5AtpjshlYiwc:-Mj54rAh8kch8BFiARAe:b-mputct) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L14)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

I think I had some edge case in mind here, but I can't remember it now :thinking: It probably wasn't important :slightly_smiling_face: 
</blockquote></details>

Was it maybe `None` vs `""`?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[generate_requirements.py, line 5 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4xl4-CUJFvdOoDASS:-Mj55smx6MyDxR9Wo4ic:b-dajkdu) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L5)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Oh yeah, I didn't see the portal was below. Shall we group them all up here or is there a reason the portal one is imported later?
</blockquote></details>

I think it was failing initially, but I may have accidentally fixed it later? I'm not sure, I can try running the action again to see if it works with it at the top as it will definitely look nicer :slightly_smiling_face: 
___
*[generate_requirements.py, line 14 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250#-Mj4xwCP5AtpjshlYiwc:-Mj56K6M2lbnuVtzSfE8:b-fjzh8z) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c365fb6721b7412d146d59e455409ca6fdc39aa6/generate_requirements.py#L14)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Was it maybe `None` vs `""`?
</blockquote></details>

Hm, not sure, we'd want the latest version with `""` too :thinking: Maybe I was thinking of `0`s and `1`s, but these get converted to strings, so it's fine :man_shrugging:

This looks good though :+1:

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
