### PR TITLE
Update agones version

### PR DESCRIPTION
**Pull request by razvan-pro**
## Description
Enabled Agones metrics and fixed version

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234)

### CODE REVIEW

**Review by dionizh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

___
*[clusters_setup/terraform/main.tf, line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234#-MUicRtnEZPa1TkK4Paw:-MUicLCL5TK9uvJ_ri4C:b-13tptn) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/68ab5dd79be1944b36d3a05f371b20428df3d069/clusters_setup/terraform/main.tf#L67)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   # Use terraform of the latest >=0.12 version
>   values = [
>     length(var.values_file) == 0 ? "" : file(var.values_file),
>   ]
> ```
</details>


Looking down below var.values_file is "" by default. Where's the 0.12 defined?

**Review by dionizh — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dionizh and @razvan-pro)

___
*[clusters_setup/terraform/main.tf, line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234#-MUicRtnEZPa1TkK4Paw:-MUidySI8vss42QYweo4:b-bts9a8) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/68ab5dd79be1944b36d3a05f371b20428df3d069/clusters_setup/terraform/main.tf#L67)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
>   # Use terraform of the latest >=0.12 version
>   values = [
>     length(var.values_file) == 0 ? "" : file(var.values_file),
>   ]
> ```

Looking down below var.values_file is "" by default. Where's the 0.12 defined?
</blockquote></details>

I think it's saying that we need terraform >=0.12 to run that operation (maybe these functions were introduced in that version) - I just copied this bit from https://github.com/googleforgames/agones/blob/main/install/terraform/modules/helm3/helm.tf :slightly_smiling_face:

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dionizh and @razvan-pro)

___
*[clusters_setup/terraform/main.tf, line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234#-MUicRtnEZPa1TkK4Paw:-MUii0Xs12biHUZfhotU:b-5242ww) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/68ab5dd79be1944b36d3a05f371b20428df3d069/clusters_setup/terraform/main.tf#L67)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

I think it's saying that we need terraform >=0.12 to run that operation (maybe these functions were introduced in that version) - I just copied this bit from https://github.com/googleforgames/agones/blob/main/install/terraform/modules/helm3/helm.tf :slightly_smiling_face: 
</blockquote></details>

Added source comment as discussed :slightly_smiling_face:

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dionizh and @razvan-pro)

___
*[clusters_setup/terraform/main.tf, line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234#-MUicRtnEZPa1TkK4Paw:-MUii7Y1-zlG8Lbe1VAg:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/68ab5dd79be1944b36d3a05f371b20428df3d069/clusters_setup/terraform/main.tf#L67)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Added source comment as discussed :slightly_smiling_face: 
</blockquote></details>

Done.

**Review by dionizh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/234#-:-MUiiUya1fd5IK5XoVns:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
