### PR TITLE
fix: Update URLs to match Django 2.0 format

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229)

### CODE REVIEW

**Review by mrniket — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[django_site/urls.py, line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229#-MLRs34c4ke5z9lV7eo4:-MLRs34c4ke5z9lV7eo5:b-qsi0lz) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/d27ebbaf99e2cd155dd61dae60d14fda23062dba/django_site/urls.py#L15)):*
> ```Python
> urlpatterns = [
>     url(r"^", include(portal_urls)),
>     url(r"^administration/", include((admin.site.urls[0], 'admin'), namespace='admin')),
> ```

do we want it in it's own namespace? does that break any reverse URL lookups?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229)* status: all files reviewed, 1 unresolved discussion (waiting on @mrniket)

___
*[django_site/urls.py, line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229#-MLRs34c4ke5z9lV7eo4:-MLSFRP0-PEKPwMrfumG:b-anckh6) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/d27ebbaf99e2cd155dd61dae60d14fda23062dba/django_site/urls.py#L15)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

do we want it in it's own namespace? does that break any reverse URL lookups?
</blockquote></details>

As far as I can tell this doesn't break anything - and it was a required change with Django 2.0
https://docs.djangoproject.com/en/3.1/releases/2.0/#features-removed-in-2-0

"Support for setting a URL instance namespace without an application namespace is removed."

**Review by mrniket — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mrniket — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[django_site/urls.py, line 16 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229#-MLvaFsT7kAaX4D_EG7s:-MLvaFsT7kAaX4D_EG7t:b-rf86ih) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c0acc32a3d290cd9066b8b63c1d136fd9a4dcb20/django_site/urls.py#L16)):*
> ```Python
> urlpatterns = [
>     url(r"^", include(portal_urls)),
>     path("admin/", admin.site.urls),
> ```

how comes we are changing the url path from "administration" to "admin"?

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @mrniket)

___
*[django_site/urls.py, line 16 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229#-MLvaFsT7kAaX4D_EG7s:-MLvs_4oBux-A0C3DhVF:b5h0lnz) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/c0acc32a3d290cd9066b8b63c1d136fd9a4dcb20/django_site/urls.py#L16)):*
<details><summary><i>Previously, mrniket (Niket Shah) wrote…</i></summary><blockquote>

how comes we are changing the url path from "administration" to "admin"?
</blockquote></details>

Woopsies :upside_down_face:

**Review by mrniket — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by mrniket — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
