### PR TITLE
GitHub actions deployment to Dev and Staging with Slack notification

### PR DESCRIPTION
**Pull request by razvan-pro**
## Description
Deploy to Dev and Staging with Slack notifications.

## Motivation and Context
Migrate from Semaphore.

## How Has This Been Tested?
Run Workflow for both dev and staging from github-actions branch. Prod will need to be tested after merging this and checking dev and staging again on master.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/241)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/241)* status: all files reviewed, 2 unresolved discussions (waiting on @razvan-pro)

___
*[notify_deployment.py, line 24 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/241#-MZIr5o-D7_dVFlUWhqA:-MZIr5o0AlHIQZsu6ITn:bph3zeo) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/2dfe28db2621a602f79d62634ad1ad6fd8360a9d/notify_deployment.py#L24)):*
> ```Python
>     message += "completed successfully :tada:"
> 
> print(message)
> ```

Print :stuck_out_tongue: 
___
*[.github/workflows/deploy_default.yml, line 68 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/241#-MZIrTPo1lU7eOUUvp3-:-MZIrTPo1lU7eOUUvp30:b-tq1g71) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/2dfe28db2621a602f79d62634ad1ad6fd8360a9d/.github/workflows/deploy_default.yml#L68)):*
> ```YAML
>       - name: Notify failed deployment
>         if: ${{ failure() }}
>         run: ./notify_deployment.py 1
> ```

Would it be possible maybe to pass in ${{ success() }} instead of 1 for example, and use that variable to print out the right message instead? That way we could have only one "notify deployment" step, and no if :smile:

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/241)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[notify_deployment.py, line 24 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/241#-MZIr5o-D7_dVFlUWhqA:-MZIyCCn1hKv5YktLgj4:b-6enbf2) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/2dfe28db2621a602f79d62634ad1ad6fd8360a9d/notify_deployment.py#L24)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Print :stuck_out_tongue: 
</blockquote></details>

Good spot :slightly_smiling_face: 
___
*[.github/workflows/deploy_default.yml, line 68 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/241#-MZIrTPo1lU7eOUUvp3-:-MZIxv9Q-qiFpRvO5Uza:b2fyk26) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/2dfe28db2621a602f79d62634ad1ad6fd8360a9d/.github/workflows/deploy_default.yml#L68)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Would it be possible maybe to pass in ${{ success() }} instead of 1 for example, and use that variable to print out the right message instead? That way we could have only one "notify deployment" step, and no if :smile: 
</blockquote></details>

Great idea! Unfortunately, it doesn't seem to work :slightly_frowning_face: `The workflow is not valid. .github/workflows/deploy_dev.yml (Line: 61, Col: 14): Unrecognized function: 'success'. Located at position 1 within expression: success()`

Docs only mention they work in the `if` conditional, so maybe it's by design to only run these steps in specific statuses, otherwise I think it skips all other steps by default (if a previous one is failing)

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/241)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[notify_deployment.py, line 24 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/241#-MZIr5o-D7_dVFlUWhqA:-MZIyyez3GPPiy2bZWT8:bms2i8n) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/2dfe28db2621a602f79d62634ad1ad6fd8360a9d/notify_deployment.py#L24)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Good spot :slightly_smiling_face: 
</blockquote></details>

Ah, actually I remember keeping this here intentionally so we can check the message in the logs if slack receives a different one somehow :smile: But it's fine to remove it I think.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/241#-:-MZJ4lcN6tKshMjg1w1v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
