### PR TITLE
GitHub actions deployment

### PR DESCRIPTION
**Pull request by razvan-pro**
This should enable us to deploy to the dev server at least by manually running a GitHub action. This manual-run functionality needs to be on the default branch, so I couldn't test it on a separate branch. However, the actual deployment worked fine on dev with a 'push' trigger.

---
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)

### CODE REVIEW

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: all files reviewed, 3 unresolved discussions (waiting on @razvan-pro)

___
*[generate_requirements.py, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3dy1s15EgwN9GXL4T:-MW3dy1s15EgwN9GXL4U:bnyonct) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/generate_requirements.py#L1)):*
> ```
> from lib.portal import __version__ as portal_version
> from lib.aimmo import __version__ as aimmo_version
> from lib.game import __version__ as rapid_router_version
> ```

Are the versions supposed to exist in the lib/__init__.py file? As it is empty right now. 
___
*[django_site/settings.py, line 178 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3gTqy66mgh8v3xv0C:-MW3gTqy66mgh8v3xv0D:b7lu3z3) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/django_site/settings.py#L178)):*
> ```
> "/cloudsql/decent-digit-629:europe-west1:db"
> ```
Should we put this into an env variable as well?
___
*[django_site/settings.py, line 180 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3gl_E05bSJA8IK_6d:-MW3gl_E05bSJA8IK_6e:bpn6tva) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/django_site/settings.py#L180)):*
> ```
> "USER": "root",
> ```
Is there no password anymore? 🤔

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: all files reviewed, 3 unresolved discussions (waiting on @dionizh and @razvan-pro)

___
*[django_site/settings.py, line 180 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3gl_E05bSJA8IK_6d:-MW4-zqa-cPe3cbElMXj:bwbtl5u) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/django_site/settings.py#L180)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> "USER": "root",
> ```
Is there no password anymore? 🤔
</blockquote></details>

:grimacing: :unlock:

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: all files reviewed, 3 unresolved discussions (waiting on @dionizh)

___
*[generate_requirements.py, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3dy1s15EgwN9GXL4T:-MWii7Q72-glD5-ZPk60:b9dg03c) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/generate_requirements.py#L1)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> from lib.portal import __version__ as portal_version
> from lib.aimmo import __version__ as aimmo_version
> from lib.game import __version__ as rapid_router_version
> ```

Are the versions supposed to exist in the lib/__init__.py file? As it is empty right now. 
</blockquote></details>

Nope, the versions will be fetched from the init of each package (portal, aimmo, game) after they are installed in lib (this happens in the "Build" step).
___
*[django_site/settings.py, line 178 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3gTqy66mgh8v3xv0C:-MWiklO323zFXJQEOlDO:bb6mt9b) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/django_site/settings.py#L178)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

> ```
> "/cloudsql/decent-digit-629:europe-west1:db"
> ```
Should we put this into an env variable as well?
</blockquote></details>

:+1:
___
*[django_site/settings.py, line 180 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3gl_E05bSJA8IK_6d:-MWiiXLv3bVvUioMNHaz:b-yuh6v1) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/django_site/settings.py#L180)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

:grimacing: :unlock: 
</blockquote></details>

Nope, because we're using cloudsql proxy now, the DB is like "local". There was never a password when the DB is "local" (to the app) - see the other "if" branch above. We can probably create users with passwords for each database/environment to increase security - though to be honest, if someone is on our gcloud, they can find ways around the passwords anyway :slightly_smiling_face:

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @dionizh)

___
*[django_site/settings.py, line 178 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3gTqy66mgh8v3xv0C:-MWin1zw09i1cD7G0a-k:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/django_site/settings.py#L178)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

Done.

**Review by dionizh — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: all files reviewed, 2 unresolved discussions (waiting on @razvan-pro)

___
*[generate_requirements.py, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3dy1s15EgwN9GXL4T:-MXBvE7HCIFj_v_SDRPv:b-is7xsz) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/generate_requirements.py#L1)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

Nope, the versions will be fetched from the init of each package (portal, aimmo, game) after they are installed in lib (this happens in the "Build" step).
</blockquote></details>

Would be helpful to have this as a comment (as there's also a `lib` folder in the repo) 🙂
___
*[django_site/settings.py, line 145 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MXByi6kC0J6hQi-_jdp:-MXByi6kC0J6hQi-_jdq:b-ushgey) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/7934e126521d0ef58064ec5d66b163e3ebd10ae5/django_site/settings.py#L145)):*
> ```Python
> }
> 
> PIPELINE_ENABLED = True
> ```

I did a quick search that PIPELINE_ENABLED is False for the other repos (aimmo, portal).

`True if assets should be compressed, False if not.` from django doc. 

I'm not sure about the actual implication, but seems leaving it to default `not settings.DEBUG.` might be ok (so we can probably remove this line). What do you think?

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: all files reviewed, 2 unresolved discussions (waiting on @dionizh)

___
*[generate_requirements.py, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3dy1s15EgwN9GXL4T:-MXC1-U65-ZmyGH9p5fU:b6h03nz) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/generate_requirements.py#L1)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Would be helpful to have this as a comment (as there's also a `lib` folder in the repo) 🙂
</blockquote></details>

They will be installed in that `lib` folder, I'm confused :thinking: 
___
*[django_site/settings.py, line 145 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MXByi6kC0J6hQi-_jdp:-MXC1Mz98f9ORnjABnal:b-urllkd) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/7934e126521d0ef58064ec5d66b163e3ebd10ae5/django_site/settings.py#L145)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

I did a quick search that PIPELINE_ENABLED is False for the other repos (aimmo, portal).

`True if assets should be compressed, False if not.` from django doc. 

I'm not sure about the actual implication, but seems leaving it to default `not settings.DEBUG.` might be ok (so we can probably remove this line). What do you think?
</blockquote></details>

This should overwrite the values in other repos :slightly_smiling_face: I don't know, I don't think it harms to be set explicitly to `True`? :shrug:

**Review by dionizh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: all files reviewed, 2 unresolved discussions (waiting on @razvan-pro)

___
*[generate_requirements.py, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3dy1s15EgwN9GXL4T:-MXC20U76VgGnvFCkO4s:b-7t510c) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/generate_requirements.py#L1)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

They will be installed in that `lib` folder, I'm confused :thinking: 
</blockquote></details>

Okay I guess it's clearer when you read the Build stage. 
___
*[django_site/settings.py, line 145 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MXByi6kC0J6hQi-_jdp:-MXC3pBM8mHHvoiSXo4O:b-x2kjnf) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/7934e126521d0ef58064ec5d66b163e3ebd10ae5/django_site/settings.py#L145)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

This should overwrite the values in other repos :slightly_smiling_face: I don't know, I don't think it harms to be set explicitly to `True`? :shrug: 
</blockquote></details>

Yea probably we want assets to be compressed. I'd put this as a comment, but up to you 🙂

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dionizh)

___
*[generate_requirements.py, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3dy1s15EgwN9GXL4T:-MXCcXV4Cdf1ulDr4ne1:b-tdv8a4) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/generate_requirements.py#L1)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Okay I guess it's clearer when you read the Build stage. 
</blockquote></details>

So, is there any comment you still feel it's needed here? :slightly_smiling_face: 
___
*[django_site/settings.py, line 145 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MXByi6kC0J6hQi-_jdp:-MXCcRyN0ezbVPa6pnd9:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/7934e126521d0ef58064ec5d66b163e3ebd10ae5/django_site/settings.py#L145)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

Yea probably we want assets to be compressed. I'd put this as a comment, but up to you 🙂
</blockquote></details>

Done.

**Review by dionizh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @dionizh and @razvan-pro)

___
*[generate_requirements.py, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3dy1s15EgwN9GXL4T:-MXCkkFz7lIaMaicUn8H:b5wh03f) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/generate_requirements.py#L1)):*
<details><summary><i>Previously, razvan-pro (Razvan Mahu) wrote…</i></summary><blockquote>

So, is there any comment you still feel it's needed here? :slightly_smiling_face: 
</blockquote></details>

I think what you said above about how 'the init of each package will be installed in lib in the Build step and that the versions will be fetched from them' would be really helpful 🙂 (so people know not to look for them or the placeholders in the current state of lib)

**Review by dionizh — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: all files reviewed, 1 unresolved discussion (waiting on @razvan-pro)

**Review by razvan-pro — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @dionizh)

___
*[generate_requirements.py, line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236#-MW3dy1s15EgwN9GXL4T:-MXDCxzF6a-D3Wr3gLMy:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-deploy-appengine/blob/0ac19a99723d902dafcfd4225b332aee7ac0e5c0/generate_requirements.py#L1)):*
<details><summary><i>Previously, dionizh (Dioni Zhong) wrote…</i></summary><blockquote>

I think what you said above about how 'the init of each package will be installed in lib in the Build step and that the versions will be fetched from them' would be really helpful 🙂 (so people know not to look for them or the placeholders in the current state of lib)
</blockquote></details>

Done.

**Review by dionizh — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-deploy-appengine/236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @razvan-pro)

**Pull request merged**
